# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'guiGPNKCK.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QFrame, QLabel, QLineEdit, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpinBox, QStackedWidget, QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1050, 602)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1050, 602))
        MainWindow.setMaximumSize(QSize(1050, 602))
        MainWindow.setBaseSize(QSize(1050, 707))
        font = QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle(u"OpenStreamControl")
        icon = QIcon()
        icon.addFile(u"wave_logo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamilies([u"Noto Sans"])
        font1.setPointSize(14)
        self.centralwidget.setFont(font1)
        self.pushButton_1 = QPushButton(self.centralwidget)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(20, 13, 131, 31))
        font2 = QFont()
        font2.setFamilies([u"Noto Sans"])
        font2.setPointSize(14)
        font2.setBold(False)
        self.pushButton_1.setFont(font2)
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 60, 131, 31))
        self.pushButton_2.setFont(font2)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(20, 110, 131, 31))
        self.pushButton_3.setFont(font1)
        self.stackedWidget_1 = QStackedWidget(self.centralwidget)
        self.stackedWidget_1.setObjectName(u"stackedWidget_1")
        self.stackedWidget_1.setEnabled(True)
        self.stackedWidget_1.setGeometry(QRect(180, 0, 861, 591))
        sizePolicy.setHeightForWidth(self.stackedWidget_1.sizePolicy().hasHeightForWidth())
        self.stackedWidget_1.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setFamilies([u"Noto Sans"])
        font3.setPointSize(14)
        font3.setKerning(False)
        self.stackedWidget_1.setFont(font3)
        self.stackedWidget_1.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.stackedWidget_1.setFrameShape(QFrame.Shape.NoFrame)
        self.stackedWidget_1.setFrameShadow(QFrame.Shadow.Plain)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.checkBox_flowenable = QCheckBox(self.page_1)
        self.checkBox_flowenable.setObjectName(u"checkBox_flowenable")
        self.checkBox_flowenable.setGeometry(QRect(590, 210, 21, 31))
        self.checkBox_flowenable.setChecked(True)
        self.checkBox_extempenable = QCheckBox(self.page_1)
        self.checkBox_extempenable.setObjectName(u"checkBox_extempenable")
        self.checkBox_extempenable.setGeometry(QRect(590, 130, 21, 31))
        self.checkBox_extempenable.setChecked(True)
        self.label_7 = QLabel(self.page_1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(460, 210, 121, 31))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_8 = QLabel(self.page_1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(450, 130, 131, 31))
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_9 = QLabel(self.page_1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 89, 151, 31))
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_10 = QLabel(self.page_1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(490, 89, 121, 31))
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_11 = QLabel(self.page_1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 209, 151, 31))
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QLabel(self.page_1)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(88, 319, 141, 31))
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_13 = QLabel(self.page_1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(98, 279, 131, 31))
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_14 = QLabel(self.page_1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(80, 399, 151, 31))
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_15 = QLabel(self.page_1)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(700, 220, 49, 16))
        self.label_16 = QLabel(self.page_1)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(700, 140, 49, 16))
        self.label_17 = QLabel(self.page_1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(78, 169, 151, 31))
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_18 = QLabel(self.page_1)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(88, 129, 141, 31))
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_19 = QLabel(self.page_1)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(90, 359, 141, 31))
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_ext_temp = QLineEdit(self.page_1)
        self.lineEdit_ext_temp.setObjectName(u"lineEdit_ext_temp")
        self.lineEdit_ext_temp.setEnabled(True)
        self.lineEdit_ext_temp.setGeometry(QRect(620, 130, 71, 31))
        self.lineEdit_ext_temp.setReadOnly(True)
        self.lineEdit_ext_temp.setClearButtonEnabled(False)
        self.lineEdit_fan_amp_temp = QLineEdit(self.page_1)
        self.lineEdit_fan_amp_temp.setObjectName(u"lineEdit_fan_amp_temp")
        self.lineEdit_fan_amp_temp.setGeometry(QRect(240, 400, 71, 31))
        self.lineEdit_fan_amp_temp.setReadOnly(True)
        self.lineEdit_temp_int = QLineEdit(self.page_1)
        self.lineEdit_temp_int.setObjectName(u"lineEdit_temp_int")
        self.lineEdit_temp_int.setGeometry(QRect(620, 90, 71, 31))
        self.lineEdit_temp_int.setReadOnly(True)
        self.lineEdit_pump_watts = QLineEdit(self.page_1)
        self.lineEdit_pump_watts.setObjectName(u"lineEdit_pump_watts")
        self.lineEdit_pump_watts.setGeometry(QRect(240, 210, 71, 31))
        self.lineEdit_pump_watts.setReadOnly(True)
        self.lineEdit_flow = QLineEdit(self.page_1)
        self.lineEdit_flow.setObjectName(u"lineEdit_flow")
        self.lineEdit_flow.setGeometry(QRect(620, 210, 71, 31))
        self.lineEdit_flow.setReadOnly(True)
        self.lineEdit_fan_pwm = QLineEdit(self.page_1)
        self.lineEdit_fan_pwm.setObjectName(u"lineEdit_fan_pwm")
        self.lineEdit_fan_pwm.setGeometry(QRect(240, 320, 71, 31))
        self.lineEdit_fan_pwm.setReadOnly(True)
        self.lineEdit_fan_speed = QLineEdit(self.page_1)
        self.lineEdit_fan_speed.setObjectName(u"lineEdit_fan_speed")
        self.lineEdit_fan_speed.setGeometry(QRect(240, 280, 71, 31))
        self.lineEdit_fan_speed.setReadOnly(True)
        self.lineEdit_pump_speed = QLineEdit(self.page_1)
        self.lineEdit_pump_speed.setObjectName(u"lineEdit_pump_speed")
        self.lineEdit_pump_speed.setGeometry(QRect(240, 90, 71, 31))
        self.lineEdit_pump_speed.setReadOnly(True)
        self.lineEdit_pump_curr = QLineEdit(self.page_1)
        self.lineEdit_pump_curr.setObjectName(u"lineEdit_pump_curr")
        self.lineEdit_pump_curr.setGeometry(QRect(240, 170, 71, 31))
        self.lineEdit_pump_curr.setReadOnly(True)
        self.lineEdit_pump_volt = QLineEdit(self.page_1)
        self.lineEdit_pump_volt.setObjectName(u"lineEdit_pump_volt")
        self.lineEdit_pump_volt.setGeometry(QRect(240, 130, 71, 31))
        self.lineEdit_pump_volt.setReadOnly(True)
        self.lineEdit_fan_volt = QLineEdit(self.page_1)
        self.lineEdit_fan_volt.setObjectName(u"lineEdit_fan_volt")
        self.lineEdit_fan_volt.setGeometry(QRect(240, 360, 71, 31))
        self.lineEdit_fan_volt.setReadOnly(True)
        self.label_20 = QLabel(self.page_1)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(320, 410, 49, 16))
        self.label_21 = QLabel(self.page_1)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(700, 100, 49, 16))
        self.label = QLabel(self.page_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(320, 370, 49, 16))
        self.label_22 = QLabel(self.page_1)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(320, 140, 49, 16))
        self.label_23 = QLabel(self.page_1)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(320, 180, 49, 16))
        self.label_24 = QLabel(self.page_1)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(320, 100, 49, 16))
        self.label_25 = QLabel(self.page_1)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(320, 290, 49, 16))
        self.label_26 = QLabel(self.page_1)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(320, 330, 49, 16))
        self.label_27 = QLabel(self.page_1)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(320, 215, 91, 21))
        self.stackedWidget_1.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.radioButton_pump_manual = QRadioButton(self.page_2)
        self.radioButton_pump_manual.setObjectName(u"radioButton_pump_manual")
        self.radioButton_pump_manual.setGeometry(QRect(20, 260, 191, 31))
        self.radioButton_pump_manual.setFont(font3)
        self.radioButton_pump_auto = QRadioButton(self.page_2)
        self.radioButton_pump_auto.setObjectName(u"radioButton_pump_auto")
        self.radioButton_pump_auto.setGeometry(QRect(20, 230, 271, 31))
        self.radioButton_pump_auto.setFont(font3)
        self.radioButton_pump_auto.setChecked(True)
        self.radioButton_pump_auto.setAutoExclusive(True)
        self.lineEdit_pump_actual_rpm = QLineEdit(self.page_2)
        self.lineEdit_pump_actual_rpm.setObjectName(u"lineEdit_pump_actual_rpm")
        self.lineEdit_pump_actual_rpm.setGeometry(QRect(760, 240, 71, 31))
        self.lineEdit_pump_actual_rpm.setFont(font3)
        self.lineEdit_pump_actual_rpm.setReadOnly(True)
        self.label_53 = QLabel(self.page_2)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(610, 240, 141, 31))
        self.label_53.setFont(font3)
        self.label_53.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.stackedWidget_pump = QStackedWidget(self.page_2)
        self.stackedWidget_pump.setObjectName(u"stackedWidget_pump")
        self.stackedWidget_pump.setGeometry(QRect(0, 320, 851, 191))
        self.stackedWidget_pump.setFont(font3)
        self.stackedWidget_pump.setFrameShape(QFrame.Shape.NoFrame)
        self.page_pump_manual = QWidget()
        self.page_pump_manual.setObjectName(u"page_pump_manual")
        self.horizontalSlider_pump_man_pump_rpm = QSlider(self.page_pump_manual)
        self.horizontalSlider_pump_man_pump_rpm.setObjectName(u"horizontalSlider_pump_man_pump_rpm")
        self.horizontalSlider_pump_man_pump_rpm.setGeometry(QRect(380, 20, 441, 21))
        self.horizontalSlider_pump_man_pump_rpm.setOrientation(Qt.Orientation.Horizontal)
        self.spinBox_pump_man_pump_rpm_hz = QSpinBox(self.page_pump_manual)
        self.spinBox_pump_man_pump_rpm_hz.setObjectName(u"spinBox_pump_man_pump_rpm_hz")
        self.spinBox_pump_man_pump_rpm_hz.setGeometry(QRect(270, 10, 61, 31))
        self.label_47 = QLabel(self.page_pump_manual)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(340, 10, 41, 31))
        self.spinBox_pump_man_pump_rpm = QSpinBox(self.page_pump_manual)
        self.spinBox_pump_man_pump_rpm.setObjectName(u"spinBox_pump_man_pump_rpm")
        self.spinBox_pump_man_pump_rpm.setGeometry(QRect(110, 10, 71, 31))
        self.spinBox_pump_man_pump_rpm.setMaximum(6000)
        self.label_30 = QLabel(self.page_pump_manual)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(-40, 10, 141, 31))
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_44 = QLabel(self.page_pump_manual)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(190, 10, 71, 31))
        self.stackedWidget_pump.addWidget(self.page_pump_manual)
        self.page_pump_auto = QWidget()
        self.page_pump_auto.setObjectName(u"page_pump_auto")
        self.label_55 = QLabel(self.page_pump_auto)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(30, 10, 71, 31))
        self.label_55.setFont(font3)
        self.label_55.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox_pump_auto_min = QSpinBox(self.page_pump_auto)
        self.spinBox_pump_auto_min.setObjectName(u"spinBox_pump_auto_min")
        self.spinBox_pump_auto_min.setGeometry(QRect(110, 50, 71, 31))
        self.spinBox_pump_auto_min.setFont(font3)
        self.spinBox_pump_auto_min.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_pump_auto_min.setMaximum(6000)
        self.spinBox_pump_auto_max_hz = QSpinBox(self.page_pump_auto)
        self.spinBox_pump_auto_max_hz.setObjectName(u"spinBox_pump_auto_max_hz")
        self.spinBox_pump_auto_max_hz.setGeometry(QRect(270, 10, 61, 31))
        self.spinBox_pump_auto_max_hz.setFont(font3)
        self.horizontalSlider_pump_auto_min = QSlider(self.page_pump_auto)
        self.horizontalSlider_pump_auto_min.setObjectName(u"horizontalSlider_pump_auto_min")
        self.horizontalSlider_pump_auto_min.setGeometry(QRect(380, 60, 441, 21))
        self.horizontalSlider_pump_auto_min.setFont(font3)
        self.horizontalSlider_pump_auto_min.setOrientation(Qt.Orientation.Horizontal)
        self.spinBox_pump_auto_max = QSpinBox(self.page_pump_auto)
        self.spinBox_pump_auto_max.setObjectName(u"spinBox_pump_auto_max")
        self.spinBox_pump_auto_max.setGeometry(QRect(110, 10, 71, 31))
        sizePolicy.setHeightForWidth(self.spinBox_pump_auto_max.sizePolicy().hasHeightForWidth())
        self.spinBox_pump_auto_max.setSizePolicy(sizePolicy)
        self.spinBox_pump_auto_max.setFont(font3)
        self.spinBox_pump_auto_max.setWrapping(False)
        self.spinBox_pump_auto_max.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.spinBox_pump_auto_max.setMinimum(0)
        self.spinBox_pump_auto_max.setMaximum(6000)
        self.spinBox_pump_auto_max.setValue(3000)
        self.label_57 = QLabel(self.page_pump_auto)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(340, 50, 31, 31))
        self.label_57.setFont(font3)
        self.checkBox_pump_auto_no_below = QCheckBox(self.page_pump_auto)
        self.checkBox_pump_auto_no_below.setObjectName(u"checkBox_pump_auto_no_below")
        self.checkBox_pump_auto_no_below.setGeometry(QRect(110, 100, 241, 20))
        self.checkBox_pump_auto_no_below.setFont(font3)
        self.label_58 = QLabel(self.page_pump_auto)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(190, 10, 61, 31))
        self.label_58.setFont(font3)
        self.horizontalSlider_pump_auto_max = QSlider(self.page_pump_auto)
        self.horizontalSlider_pump_auto_max.setObjectName(u"horizontalSlider_pump_auto_max")
        self.horizontalSlider_pump_auto_max.setGeometry(QRect(380, 20, 441, 21))
        self.horizontalSlider_pump_auto_max.setFont(font3)
        self.horizontalSlider_pump_auto_max.setOrientation(Qt.Orientation.Horizontal)
        self.label_59 = QLabel(self.page_pump_auto)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 50, 91, 31))
        self.label_59.setFont(font3)
        self.label_59.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_60 = QLabel(self.page_pump_auto)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(340, 15, 31, 21))
        self.label_60.setFont(font3)
        self.label_61 = QLabel(self.page_pump_auto)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(190, 50, 51, 31))
        self.label_61.setFont(font3)
        self.spinBox_pump_auto_min_hz = QSpinBox(self.page_pump_auto)
        self.spinBox_pump_auto_min_hz.setObjectName(u"spinBox_pump_auto_min_hz")
        self.spinBox_pump_auto_min_hz.setGeometry(QRect(270, 50, 61, 31))
        self.spinBox_pump_auto_min_hz.setFont(font3)
        self.stackedWidget_pump.addWidget(self.page_pump_auto)
        self.pushButton_pump_save_to_pump = QPushButton(self.page_2)
        self.pushButton_pump_save_to_pump.setObjectName(u"pushButton_pump_save_to_pump")
        self.pushButton_pump_save_to_pump.setGeometry(QRect(10, 520, 151, 61))
        self.pushButton_pump_save_to_pump.setFont(font3)
        self.line_2 = QFrame(self.page_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 290, 861, 20))
        self.line_2.setFont(font3)
        self.line_2.setFrameShadow(QFrame.Shadow.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.plotWidget_pump = PlotWidget(self.page_2)
        self.plotWidget_pump.setObjectName(u"plotWidget_pump")
        self.plotWidget_pump.setGeometry(QRect(30, 30, 801, 191))
        self.label_54 = QLabel(self.page_2)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(390, 230, 141, 51))
        self.label_54.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_pump_current_graph = QLineEdit(self.page_2)
        self.lineEdit_pump_current_graph.setObjectName(u"lineEdit_pump_current_graph")
        self.lineEdit_pump_current_graph.setGeometry(QRect(540, 240, 61, 31))
        self.stackedWidget_1.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.radioButton_fans_auto = QRadioButton(self.page_3)
        self.radioButton_fans_auto.setObjectName(u"radioButton_fans_auto")
        self.radioButton_fans_auto.setGeometry(QRect(20, 230, 161, 31))
        self.radioButton_fans_auto.setFont(font3)
        self.radioButton_fans_man = QRadioButton(self.page_3)
        self.radioButton_fans_man.setObjectName(u"radioButton_fans_man")
        self.radioButton_fans_man.setGeometry(QRect(20, 260, 161, 31))
        self.radioButton_fans_man.setFont(font3)
        self.pushButton_fans_save_to_pump = QPushButton(self.page_3)
        self.pushButton_fans_save_to_pump.setObjectName(u"pushButton_fans_save_to_pump")
        self.pushButton_fans_save_to_pump.setGeometry(QRect(10, 520, 151, 61))
        self.pushButton_fans_save_to_pump.setFont(font3)
        self.pushButton_fans_save_to_pump.setAutoExclusive(False)
        self.pushButton_fans_save_to_pump.setAutoDefault(False)
        self.pushButton_fans_save_to_pump.setFlat(False)
        self.stackedWidget_fans = QStackedWidget(self.page_3)
        self.stackedWidget_fans.setObjectName(u"stackedWidget_fans")
        self.stackedWidget_fans.setGeometry(QRect(0, 320, 851, 201))
        self.stackedWidget_fans.setFont(font3)
        self.stackedWidget_fans.setFrameShape(QFrame.Shape.NoFrame)
        self.page_fans_auto = QWidget()
        self.page_fans_auto.setObjectName(u"page_fans_auto")
        self.spinBox_fans_auto_target_temp = QSpinBox(self.page_fans_auto)
        self.spinBox_fans_auto_target_temp.setObjectName(u"spinBox_fans_auto_target_temp")
        self.spinBox_fans_auto_target_temp.setGeometry(QRect(170, 150, 61, 31))
        self.spinBox_fans_auto_target_temp.setFont(font3)
        self.label_28 = QLabel(self.page_fans_auto)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 150, 151, 31))
        self.label_28.setFont(font3)
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.radioButton_fans_auto_int_temp = QRadioButton(self.page_fans_auto)
        self.radioButton_fans_auto_int_temp.setObjectName(u"radioButton_fans_auto_int_temp")
        self.radioButton_fans_auto_int_temp.setGeometry(QRect(290, 170, 171, 31))
        self.radioButton_fans_auto_int_temp.setFont(font3)
        self.radioButton_fans_auto_ext_temp = QRadioButton(self.page_fans_auto)
        self.radioButton_fans_auto_ext_temp.setObjectName(u"radioButton_fans_auto_ext_temp")
        self.radioButton_fans_auto_ext_temp.setGeometry(QRect(290, 130, 181, 31))
        self.radioButton_fans_auto_ext_temp.setFont(font3)
        self.label_48 = QLabel(self.page_fans_auto)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(30, 10, 81, 31))
        self.label_48.setFont(font3)
        self.label_48.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_49 = QLabel(self.page_fans_auto)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(30, 50, 81, 31))
        self.label_49.setFont(font3)
        self.label_49.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox_fans_auto_fans_min_hz = QSpinBox(self.page_fans_auto)
        self.spinBox_fans_auto_fans_min_hz.setObjectName(u"spinBox_fans_auto_fans_min_hz")
        self.spinBox_fans_auto_fans_min_hz.setGeometry(QRect(120, 10, 61, 31))
        self.spinBox_fans_auto_fans_min_hz.setFont(font3)
        self.spinBox_fans_auto_fans_max_hz = QSpinBox(self.page_fans_auto)
        self.spinBox_fans_auto_fans_max_hz.setObjectName(u"spinBox_fans_auto_fans_max_hz")
        self.spinBox_fans_auto_fans_max_hz.setGeometry(QRect(120, 50, 61, 31))
        self.spinBox_fans_auto_fans_max_hz.setFont(font3)
        self.checkBox_fans_auto_hold_min = QCheckBox(self.page_fans_auto)
        self.checkBox_fans_auto_hold_min.setObjectName(u"checkBox_fans_auto_hold_min")
        self.checkBox_fans_auto_hold_min.setGeometry(QRect(120, 90, 171, 20))
        self.checkBox_fans_auto_hold_min.setFont(font3)
        self.label_50 = QLabel(self.page_fans_auto)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(190, 10, 51, 31))
        self.label_50.setFont(font3)
        self.label_51 = QLabel(self.page_fans_auto)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(190, 50, 41, 31))
        self.label_51.setFont(font3)
        self.horizontalSlider_fans_auto_min = QSlider(self.page_fans_auto)
        self.horizontalSlider_fans_auto_min.setObjectName(u"horizontalSlider_fans_auto_min")
        self.horizontalSlider_fans_auto_min.setGeometry(QRect(230, 19, 601, 21))
        self.horizontalSlider_fans_auto_min.setFont(font3)
        self.horizontalSlider_fans_auto_min.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider_fans_auto_max = QSlider(self.page_fans_auto)
        self.horizontalSlider_fans_auto_max.setObjectName(u"horizontalSlider_fans_auto_max")
        self.horizontalSlider_fans_auto_max.setGeometry(QRect(230, 60, 601, 21))
        self.horizontalSlider_fans_auto_max.setFont(font3)
        self.horizontalSlider_fans_auto_max.setOrientation(Qt.Orientation.Horizontal)
        self.label_52 = QLabel(self.page_fans_auto)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(590, 120, 161, 31))
        self.label_52.setFont(font3)
        self.label_52.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.comboBox_fans_pid = QComboBox(self.page_fans_auto)
        self.comboBox_fans_pid.addItem("")
        self.comboBox_fans_pid.addItem("")
        self.comboBox_fans_pid.addItem("")
        self.comboBox_fans_pid.addItem("")
        self.comboBox_fans_pid.addItem("")
        self.comboBox_fans_pid.setObjectName(u"comboBox_fans_pid")
        self.comboBox_fans_pid.setEnabled(True)
        self.comboBox_fans_pid.setGeometry(QRect(590, 160, 201, 41))
        self.comboBox_fans_pid.setFont(font3)
        self.comboBox_fans_pid.setCurrentText(u"Minimum -2")
        self.comboBox_fans_pid.setInsertPolicy(QComboBox.InsertPolicy.InsertAlphabetically)
        self.comboBox_fans_pid.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_fans_pid.setFrame(True)
        self.lineEdit_fans_auto_temp_int = QLineEdit(self.page_fans_auto)
        self.lineEdit_fans_auto_temp_int.setObjectName(u"lineEdit_fans_auto_temp_int")
        self.lineEdit_fans_auto_temp_int.setGeometry(QRect(470, 170, 51, 31))
        self.lineEdit_fans_auto_temp_int.setFont(font3)
        self.lineEdit_fans_auto_temp_ext = QLineEdit(self.page_fans_auto)
        self.lineEdit_fans_auto_temp_ext.setObjectName(u"lineEdit_fans_auto_temp_ext")
        self.lineEdit_fans_auto_temp_ext.setGeometry(QRect(470, 130, 51, 31))
        self.lineEdit_fans_auto_temp_ext.setFont(font3)
        self.stackedWidget_fans.addWidget(self.page_fans_auto)
        self.page_fans_manual = QWidget()
        self.page_fans_manual.setObjectName(u"page_fans_manual")
        self.spinBox_fans_man = QSpinBox(self.page_fans_manual)
        self.spinBox_fans_man.setObjectName(u"spinBox_fans_man")
        self.spinBox_fans_man.setGeometry(QRect(120, 10, 61, 31))
        self.label_64 = QLabel(self.page_fans_manual)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(40, 10, 71, 31))
        self.label_64.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_65 = QLabel(self.page_fans_manual)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(190, 10, 31, 31))
        self.horizontalSlider_fans_man = QSlider(self.page_fans_manual)
        self.horizontalSlider_fans_man.setObjectName(u"horizontalSlider_fans_man")
        self.horizontalSlider_fans_man.setGeometry(QRect(230, 19, 601, 21))
        self.horizontalSlider_fans_man.setOrientation(Qt.Orientation.Horizontal)
        self.stackedWidget_fans.addWidget(self.page_fans_manual)
        self.line_3 = QFrame(self.page_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-10, 285, 861, 31))
        self.line_3.setFont(font3)
        self.line_3.setFrameShadow(QFrame.Shadow.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.lineEdit_fans_fan_speed = QLineEdit(self.page_3)
        self.lineEdit_fans_fan_speed.setObjectName(u"lineEdit_fans_fan_speed")
        self.lineEdit_fans_fan_speed.setGeometry(QRect(760, 240, 71, 31))
        self.lineEdit_fans_fan_speed.setFont(font3)
        self.lineEdit_fans_fan_speed.setReadOnly(True)
        self.label_66 = QLabel(self.page_3)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(620, 240, 131, 31))
        self.label_66.setFont(font3)
        self.label_66.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_fans_pwm_graph = QLineEdit(self.page_3)
        self.lineEdit_fans_pwm_graph.setObjectName(u"lineEdit_fans_pwm_graph")
        self.lineEdit_fans_pwm_graph.setGeometry(QRect(540, 240, 61, 31))
        self.label_29 = QLabel(self.page_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(420, 240, 111, 31))
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.plotWidget_fans = PlotWidget(self.page_3)
        self.plotWidget_fans.setObjectName(u"plotWidget_fans")
        self.plotWidget_fans.setGeometry(QRect(30, 30, 801, 191))
        self.stackedWidget_1.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.pushButton_ctrl_report = QPushButton(self.page_4)
        self.pushButton_ctrl_report.setObjectName(u"pushButton_ctrl_report")
        self.pushButton_ctrl_report.setGeometry(QRect(550, 540, 271, 31))
        self.pushButton_sensor_report = QPushButton(self.page_4)
        self.pushButton_sensor_report.setObjectName(u"pushButton_sensor_report")
        self.pushButton_sensor_report.setGeometry(QRect(550, 510, 271, 31))
        self.spinBox_settings_flow_calib = QSpinBox(self.page_4)
        self.spinBox_settings_flow_calib.setObjectName(u"spinBox_settings_flow_calib")
        self.spinBox_settings_flow_calib.setGeometry(QRect(40, 340, 81, 31))
        self.spinBox_settings_flow_calib.setMinimum(1)
        self.spinBox_settings_flow_calib.setMaximum(1000)
        self.label_6 = QLabel(self.page_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 340, 361, 31))
        self.lineEdit_settings_flow = QLineEdit(self.page_4)
        self.lineEdit_settings_flow.setObjectName(u"lineEdit_settings_flow")
        self.lineEdit_settings_flow.setGeometry(QRect(40, 380, 81, 31))
        self.lineEdit_settings_flow.setReadOnly(True)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(130, 380, 111, 31))
        self.lineEdit_settings_firmware = QLineEdit(self.page_4)
        self.lineEdit_settings_firmware.setObjectName(u"lineEdit_settings_firmware")
        self.lineEdit_settings_firmware.setEnabled(False)
        self.lineEdit_settings_firmware.setGeometry(QRect(180, 50, 161, 21))
        self.lineEdit_settings_firmware.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_settings_firmware.setReadOnly(True)
        self.lineEdit_settings_device_key = QLineEdit(self.page_4)
        self.lineEdit_settings_device_key.setObjectName(u"lineEdit_settings_device_key")
        self.lineEdit_settings_device_key.setEnabled(False)
        self.lineEdit_settings_device_key.setGeometry(QRect(180, 130, 331, 21))
        font4 = QFont()
        font4.setFamilies([u"Noto Sans"])
        font4.setPointSize(13)
        font4.setKerning(False)
        self.lineEdit_settings_device_key.setFont(font4)
        self.lineEdit_settings_device_key.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_settings_device_key.setReadOnly(True)
        self.lineEdit_settings_serial = QLineEdit(self.page_4)
        self.lineEdit_settings_serial.setObjectName(u"lineEdit_settings_serial")
        self.lineEdit_settings_serial.setEnabled(False)
        self.lineEdit_settings_serial.setGeometry(QRect(180, 90, 161, 21))
        self.lineEdit_settings_serial.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_settings_serial.setReadOnly(True)
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setEnabled(False)
        self.label_32.setGeometry(QRect(40, 49, 131, 21))
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setEnabled(False)
        self.label_33.setGeometry(QRect(40, 130, 131, 20))
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setEnabled(False)
        self.label_34.setGeometry(QRect(40, 90, 131, 20))
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.radioButton_source_fan = QRadioButton(self.page_4)
        self.radioButton_source_fan.setObjectName(u"radioButton_source_fan")
        self.radioButton_source_fan.setGeometry(QRect(550, 60, 171, 20))
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setEnabled(True)
        self.label_35.setGeometry(QRect(550, 200, 161, 41))
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(550, 20, 231, 41))
        self.radioButton_source_flow = QRadioButton(self.page_4)
        self.radioButton_source_flow.setObjectName(u"radioButton_source_flow")
        self.radioButton_source_flow.setGeometry(QRect(550, 80, 171, 20))
        self.radioButton_source_pump = QRadioButton(self.page_4)
        self.radioButton_source_pump.setObjectName(u"radioButton_source_pump")
        self.radioButton_source_pump.setGeometry(QRect(550, 100, 191, 20))
        self.radioButton_source_static = QRadioButton(self.page_4)
        self.radioButton_source_static.setObjectName(u"radioButton_source_static")
        self.radioButton_source_static.setGeometry(QRect(550, 120, 171, 20))
        self.pushButton_settings_save_to_pump = QPushButton(self.page_4)
        self.pushButton_settings_save_to_pump.setObjectName(u"pushButton_settings_save_to_pump")
        self.pushButton_settings_save_to_pump.setGeometry(QRect(10, 520, 151, 61))
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(230, 470, 101, 41))
        self.checkBox_source_turn_off_when_alarm = QCheckBox(self.page_4)
        self.checkBox_source_turn_off_when_alarm.setObjectName(u"checkBox_source_turn_off_when_alarm")
        self.checkBox_source_turn_off_when_alarm.setGeometry(QRect(550, 140, 231, 21))
        self.checkBox_alarm_pump = QCheckBox(self.page_4)
        self.checkBox_alarm_pump.setObjectName(u"checkBox_alarm_pump")
        self.checkBox_alarm_pump.setEnabled(True)
        self.checkBox_alarm_pump.setGeometry(QRect(550, 240, 141, 20))
        self.checkBox_alarm_int_temp = QCheckBox(self.page_4)
        self.checkBox_alarm_int_temp.setObjectName(u"checkBox_alarm_int_temp")
        self.checkBox_alarm_int_temp.setEnabled(True)
        self.checkBox_alarm_int_temp.setGeometry(QRect(550, 260, 141, 20))
        self.checkBox_alarm_ext_temp = QCheckBox(self.page_4)
        self.checkBox_alarm_ext_temp.setObjectName(u"checkBox_alarm_ext_temp")
        self.checkBox_alarm_ext_temp.setEnabled(True)
        self.checkBox_alarm_ext_temp.setGeometry(QRect(550, 280, 141, 20))
        self.checkBox_alarm_flow = QCheckBox(self.page_4)
        self.checkBox_alarm_flow.setObjectName(u"checkBox_alarm_flow")
        self.checkBox_alarm_flow.setEnabled(True)
        self.checkBox_alarm_flow.setGeometry(QRect(550, 300, 131, 20))
        self.checkBox_alarm_fan_rpm = QCheckBox(self.page_4)
        self.checkBox_alarm_fan_rpm.setObjectName(u"checkBox_alarm_fan_rpm")
        self.checkBox_alarm_fan_rpm.setEnabled(True)
        self.checkBox_alarm_fan_rpm.setGeometry(QRect(550, 320, 151, 20))
        self.checkBox_alarm_fan_overload = QCheckBox(self.page_4)
        self.checkBox_alarm_fan_overload.setObjectName(u"checkBox_alarm_fan_overload")
        self.checkBox_alarm_fan_overload.setEnabled(True)
        self.checkBox_alarm_fan_overload.setGeometry(QRect(550, 340, 211, 20))
        self.checkBox_alarm_80 = QCheckBox(self.page_4)
        self.checkBox_alarm_80.setObjectName(u"checkBox_alarm_80")
        self.checkBox_alarm_80.setEnabled(True)
        self.checkBox_alarm_80.setGeometry(QRect(550, 360, 201, 20))
        self.checkBox_alarm_100 = QCheckBox(self.page_4)
        self.checkBox_alarm_100.setObjectName(u"checkBox_alarm_100")
        self.checkBox_alarm_100.setEnabled(True)
        self.checkBox_alarm_100.setGeometry(QRect(550, 380, 201, 20))
        self.checkBox_alarm_100.setCheckable(True)
        self.spinBox_alarm_int_temp_max = QSpinBox(self.page_4)
        self.spinBox_alarm_int_temp_max.setObjectName(u"spinBox_alarm_int_temp_max")
        self.spinBox_alarm_int_temp_max.setEnabled(True)
        self.spinBox_alarm_int_temp_max.setGeometry(QRect(700, 260, 61, 22))
        self.spinBox_alarm_int_temp_max.setMinimum(1)
        self.spinBox_alarm_ext_temp_max = QSpinBox(self.page_4)
        self.spinBox_alarm_ext_temp_max.setObjectName(u"spinBox_alarm_ext_temp_max")
        self.spinBox_alarm_ext_temp_max.setEnabled(True)
        self.spinBox_alarm_ext_temp_max.setGeometry(QRect(700, 280, 61, 22))
        self.spinBox_alarm_ext_temp_max.setMinimum(1)
        self.spinBox_alarm_flow_min = QSpinBox(self.page_4)
        self.spinBox_alarm_flow_min.setObjectName(u"spinBox_alarm_flow_min")
        self.spinBox_alarm_flow_min.setEnabled(True)
        self.spinBox_alarm_flow_min.setGeometry(QRect(700, 300, 61, 22))
        self.spinBox_alarm_flow_min.setMinimum(1)
        self.spinBox_alarm_flow_min.setMaximum(1000)
        self.spinBox_settings_ext_offset = QSpinBox(self.page_4)
        self.spinBox_settings_ext_offset.setObjectName(u"spinBox_settings_ext_offset")
        self.spinBox_settings_ext_offset.setGeometry(QRect(40, 190, 61, 31))
        self.spinBox_settings_ext_offset.setMinimum(-100)
        self.spinBox_settings_ext_offset.setMaximum(100)
        self.spinBox_settings_int_offset = QSpinBox(self.page_4)
        self.spinBox_settings_int_offset.setObjectName(u"spinBox_settings_int_offset")
        self.spinBox_settings_int_offset.setGeometry(QRect(40, 230, 61, 31))
        self.spinBox_settings_int_offset.setMinimum(-100)
        self.spinBox_settings_int_offset.setMaximum(100)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(110, 190, 171, 31))
        self.label_38.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(110, 230, 181, 31))
        self.label_39.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setEnabled(True)
        self.label_40.setGeometry(QRect(770, 260, 71, 16))
        self.label_41 = QLabel(self.page_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setEnabled(True)
        self.label_41.setGeometry(QRect(770, 280, 81, 16))
        self.label_42 = QLabel(self.page_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setEnabled(True)
        self.label_42.setGeometry(QRect(770, 300, 101, 16))
        self.line_4 = QFrame(self.page_4)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 430, 851, 16))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_flow_active = QLabel(self.page_4)
        self.label_flow_active.setObjectName(u"label_flow_active")
        self.label_flow_active.setEnabled(True)
        self.label_flow_active.setGeometry(QRect(40, 310, 171, 24))
        palette = QPalette()
        brush = QBrush(QColor(45, 188, 74, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        self.label_flow_active.setPalette(palette)
        self.label_aquabus_active = QLabel(self.page_4)
        self.label_aquabus_active.setObjectName(u"label_aquabus_active")
        self.label_aquabus_active.setEnabled(True)
        self.label_aquabus_active.setGeometry(QRect(40, 290, 271, 24))
        palette1 = QPalette()
        brush1 = QBrush(QColor(255, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        self.label_aquabus_active.setPalette(palette1)
        self.pushButton_save_reports_to_disk = QPushButton(self.page_4)
        self.pushButton_save_reports_to_disk.setObjectName(u"pushButton_save_reports_to_disk")
        self.pushButton_save_reports_to_disk.setGeometry(QRect(230, 510, 311, 31))
        self.lineEdit_ctrl_report_file_name = QLineEdit(self.page_4)
        self.lineEdit_ctrl_report_file_name.setObjectName(u"lineEdit_ctrl_report_file_name")
        self.lineEdit_ctrl_report_file_name.setGeometry(QRect(230, 540, 311, 31))
        self.lineEdit_ctrl_report_file_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_5 = QFrame(self.page_4)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(180, 440, 16, 151))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.stackedWidget_1.addWidget(self.page_4)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 160, 131, 31))
        self.pushButton_4.setFont(font1)
        self.lineEdit_model = QLineEdit(self.centralwidget)
        self.lineEdit_model.setObjectName(u"lineEdit_model")
        self.lineEdit_model.setEnabled(False)
        self.lineEdit_model.setGeometry(QRect(10, 550, 141, 31))
        font5 = QFont()
        font5.setFamilies([u"Noto Sans"])
        font5.setPointSize(12)
        self.lineEdit_model.setFont(font5)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(160, 10, 20, 581))
        self.line.setFont(font1)
        self.line.setFrameShadow(QFrame.Shadow.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QRect(10, 530, 131, 21))
        self.label_5.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.pushButton_1.setDefault(True)
        self.stackedWidget_1.setCurrentIndex(3)
        self.stackedWidget_pump.setCurrentIndex(1)
        self.stackedWidget_fans.setCurrentIndex(0)
        self.comboBox_fans_pid.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"Sensors", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Pump", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Fans", None))
        self.checkBox_flowenable.setText("")
        self.checkBox_extempenable.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Flow Sensor", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Temp Ext", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Pump Speed", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Temp Int", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Pump Watts", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Fan pwm", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Fan Speed", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Temp Fan Amp", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"l/h", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Pump Current", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Pump Voltage", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Fan Voltage", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"rpm", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"rpm", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"W", None))
        self.radioButton_pump_manual.setText(QCoreApplication.translate("MainWindow", u"&Manual", None))
        self.radioButton_pump_auto.setText(QCoreApplication.translate("MainWindow", u"Automatic / max &power", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Pump Speed", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Pump", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"R/min", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Max", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.checkBox_pump_auto_no_below.setText(QCoreApplication.translate("MainWindow", u"Dont go below min rpm", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"R/min", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"R/min", None))
        self.pushButton_pump_save_to_pump.setText(QCoreApplication.translate("MainWindow", u"Apply \n"
"Save to Pump", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Pump Current", None))
        self.radioButton_fans_auto.setText(QCoreApplication.translate("MainWindow", u"A&utomatic", None))
        self.radioButton_fans_man.setText(QCoreApplication.translate("MainWindow", u"&Manual", None))
        self.pushButton_fans_save_to_pump.setText(QCoreApplication.translate("MainWindow", u"Apply \n"
"Save to Pump", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Target Temp", None))
        self.radioButton_fans_auto_int_temp.setText(QCoreApplication.translate("MainWindow", u"Int &Temp Sensor", None))
        self.radioButton_fans_auto_ext_temp.setText(QCoreApplication.translate("MainWindow", u"Ext Temp &Sensor", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Fan Min", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Fan Max", None))
        self.checkBox_fans_auto_hold_min.setText(QCoreApplication.translate("MainWindow", u"Hold Min", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"PID Controller", None))
        self.comboBox_fans_pid.setItemText(0, QCoreApplication.translate("MainWindow", u"Minimum -2", None))
        self.comboBox_fans_pid.setItemText(1, QCoreApplication.translate("MainWindow", u"Slower -1", None))
        self.comboBox_fans_pid.setItemText(2, QCoreApplication.translate("MainWindow", u"Normal Speed", None))
        self.comboBox_fans_pid.setItemText(3, QCoreApplication.translate("MainWindow", u"Faster +1", None))
        self.comboBox_fans_pid.setItemText(4, QCoreApplication.translate("MainWindow", u"Maximum +2", None))

        self.comboBox_fans_pid.setPlaceholderText("")
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Fan", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Fan Speed", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Fan pwm", None))
        self.pushButton_ctrl_report.setText(QCoreApplication.translate("MainWindow", u"get and print ctrl report", None))
        self.pushButton_sensor_report.setText(QCoreApplication.translate("MainWindow", u"get and print sensor report", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Flow Sensor Calibration Inpulses/Liter", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Flow l/h", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Firmware", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Device Key", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Serial number", None))
        self.radioButton_source_fan.setText(QCoreApplication.translate("MainWindow", u"Fa&n", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Alarms", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Source of Rpm Output", None))
        self.radioButton_source_flow.setText(QCoreApplication.translate("MainWindow", u"F&low", None))
        self.radioButton_source_pump.setText(QCoreApplication.translate("MainWindow", u"&Pump", None))
        self.radioButton_source_static.setText(QCoreApplication.translate("MainWindow", u"&Static", None))
        self.pushButton_settings_save_to_pump.setText(QCoreApplication.translate("MainWindow", u"Apply \n"
"Save to Pump", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"debug", None))
        self.checkBox_source_turn_off_when_alarm.setText(QCoreApplication.translate("MainWindow", u"Turn off when Alarm", None))
        self.checkBox_alarm_pump.setText(QCoreApplication.translate("MainWindow", u"Pump", None))
        self.checkBox_alarm_int_temp.setText(QCoreApplication.translate("MainWindow", u"Int Temp \u00b0C", None))
        self.checkBox_alarm_ext_temp.setText(QCoreApplication.translate("MainWindow", u"Ext Temp \u00b0C", None))
        self.checkBox_alarm_flow.setText(QCoreApplication.translate("MainWindow", u"Flow l/h", None))
        self.checkBox_alarm_fan_rpm.setText(QCoreApplication.translate("MainWindow", u"Fan Rpm", None))
        self.checkBox_alarm_fan_overload.setText(QCoreApplication.translate("MainWindow", u"Overload Fan Output", None))
        self.checkBox_alarm_80.setText(QCoreApplication.translate("MainWindow", u"Fan Output > 80\u00b0C", None))
        self.checkBox_alarm_100.setText(QCoreApplication.translate("MainWindow", u"Fan Output > 100\u00b0C", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Ext Temp Offset", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Int Temp Offset", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"max", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"max", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"min", None))
        self.label_flow_active.setText(QCoreApplication.translate("MainWindow", u"-> Flow Sensor", None))
        self.label_aquabus_active.setText(QCoreApplication.translate("MainWindow", u"-> Aquabus (not supported)", None))
        self.pushButton_save_reports_to_disk.setText(QCoreApplication.translate("MainWindow", u"save reports to disk", None))
        self.lineEdit_ctrl_report_file_name.setText(QCoreApplication.translate("MainWindow", u"my_report_xy", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.lineEdit_model.setText(QCoreApplication.translate("MainWindow", u"none", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Pump found:", None))
        pass
    # retranslateUi

